include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  exclude:
    - lib/injection.config.dart

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    # sort_constructors_first: false
