name: nota
description: a Notes app with Flutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cloud_firestore: ^4.0.1
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_auth_platform_interface: ^6.11.11
  firebase_core: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.2.1
  fpdart: ^0.4.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.0.7
  google_sign_in: ^5.4.2
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.4
  json_serializable: ^6.5.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter_icons:
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_launcher_icons:main
  image_path: "assets/icons/nota-icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/nota-icon.png"

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  # integrations:
  #   flutter_svg: true
  #   flare_flutter: true
  #   rive: true
  #   lottie: true

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  color: "#FFFFFF"
  image: assets/icons/nota-icon.png
  color_dark: "#1B1A24"
  image_dark: assets/icons/nota-icon.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
