name: nota
description: a Notes app with Flutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_icons:
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_launcher_icons:main
  image_path: "assets/icons/nota-icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/nota-icon.png"

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  color: "#FFFFFF"
  image: assets/icons/nota-icon.png
  color_dark: "#1B1A24"
  image_dark: assets/icons/nota-icon.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
