name: nota
description: a Notes app with Flutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_icons:
  image_path: "assets/icons/nota-icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  #background_image: "assets/background.png"
  image: assets/icons/nota-icon.png
  color_dark: "#1B1A24"
  image_dark: assets/icons/nota-icon.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
