// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEpWq6IqYE79VafTMt0Rj0k4nwoZO7Vo',
    appId: '1:421718850828:web:00d81dbae5fa5bade2dd29',
    messagingSenderId: '421718850828',
    projectId: 'nota-71534',
    authDomain: 'nota-71534.firebaseapp.com',
    databaseURL: 'https://nota-71534.firebaseio.com',
    storageBucket: 'nota-71534.appspot.com',
    measurementId: 'G-BW13JRLDSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKVzkCpaHJ2sQRliR-yTv_jWwFr7SAoo',
    appId: '1:421718850828:android:c495b18ccf4f1a72e2dd29',
    messagingSenderId: '421718850828',
    projectId: 'nota-71534',
    databaseURL: 'https://nota-71534.firebaseio.com',
    storageBucket: 'nota-71534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA9uX-dRU5ehato2ME4owsZglqJZZiMqE',
    appId: '1:421718850828:ios:97d2cd77ffbce9ede2dd29',
    messagingSenderId: '421718850828',
    projectId: 'nota-71534',
    databaseURL: 'https://nota-71534.firebaseio.com',
    storageBucket: 'nota-71534.appspot.com',
    androidClientId:
        '421718850828-204arohss2rlqndu1vrsoum3th3akfjp.apps.googleusercontent.com',
    iosClientId:
        '421718850828-4sd7d8atnd56igrra49plg8nllrppf8r.apps.googleusercontent.com',
    iosBundleId: 'dev.jarjut.nota',
  );
}
